services:
  database:
    image: postgres:15-alpine
    container_name: task-system-db
    environment:
      POSTGRES_USER: taskuser
      POSTGRES_PASSWORD: taskpass123
      POSTGRES_DB: taskdb
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - task-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U taskuser -d taskdb"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  backend:
    image: vladyslavkuliavets/task-management-backend:latest
    container_name: task-system-backend
    environment:
      NODE_ENV: production
      DB_HOST: database
      DB_PORT: 5432
      DB_NAME: taskdb
      DB_USER: taskuser
      DB_PASSWORD: taskpass123
      PORT: 3000
    ports:
      - "3000:3000"
    depends_on:
      database:
        condition: service_healthy
    networks:
      - task-network
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  frontend:
    image: vladyslavkuliavets/task-management-frontend:latest
    container_name: task-system-frontend
    environment:
      VITE_API_URL: http://localhost:3000
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - task-network
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  watchtower:
    image: containrrr/watchtower
    container_name: task-system-watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_POLL_INTERVAL=60  
      - WATCHTOWER_CLEANUP=true      
      - WATCHTOWER_INCLUDE_STOPPED=false
      - WATCHTOWER_LABEL_ENABLE=true 
      - WATCHTOWER_DEBUG=true        
    networks:
      - task-network
    restart: unless-stopped
    command: --interval 60

volumes:
  postgres_data:

networks:
  task-network:
    driver: bridge
