name: Docker Security Scan

on:
  schedule:
    - cron: '0 2 * * 0'  # Weekly on Sunday at 2 AM
  workflow_dispatch:

jobs:
  security-scan:
    name: Security Vulnerability Scan
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Trivy vulnerability scanner - Backend
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: './backend'
          format: 'sarif'
          output: 'trivy-backend-results.sarif'

      - name: Run Trivy vulnerability scanner - Frontend
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: './frontend'
          format: 'sarif'
          output: 'trivy-frontend-results.sarif'

      - name: Upload Trivy results to GitHub Security
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: '.'

      - name: Build Docker images for scanning
        run: |
          docker build -t backend-scan:latest ./backend
          docker build -t frontend-scan:latest ./frontend

      - name: Scan backend Docker image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'backend-scan:latest'
          format: 'table'
          exit-code: '0'
          severity: 'CRITICAL,HIGH'

      - name: Scan frontend Docker image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'frontend-scan:latest'
          format: 'table'
          exit-code: '0'
          severity: 'CRITICAL,HIGH'
